var questions = [
    ["mc",
    "The meningeal layer intimately associated with the surface of the brain is known as",
    "Epidural Mater",
    "Dura Mater",
    "Arachnoid Mater",
    "Subarachnoid Mater",
    "Pia Mater",
    "E"],
    ["mc", 
    "The layers and spaces surrounding the brain from outer to inner, in order, are", 
    "Arachnoid mater, Subarachnoid space, Dura Mater, Epidural Space, Subdural Space, Pia mater", 
    "Epidural Space, Dura Mater, Subdural Space, Arachnoid Mater, Subarachnoid Space, Pia Mater", 
    "Pia Mater, Subpial Space, Arachnoid Mater, Subarachnoid Space, Dura Mater, Subdural Space",  
    "Epidural Space, Dura Mater, Subdural Space, Pia Mater, Subarachnoid Space, Arachnoid Mater",
    "Arachnoid Mater, Subarachnoid Space, Pia Mater, Epidural Space, Dura Mater, Subdural Space",
    "B"],
    ["mc",
    "The only bone of the calvarium that is unpaired is the",
    "Frontal",
    "Parietal",
    "Temporal",
    "Occipital",
    "Zygomatic",
    "D"],
    ["mc",
    "The Third Ventricle Drains Directly into the",
    "Lateral Ventricle",
    "Occipital Horn",
    "Cerebral Aqueduct",
    "Fourth Ventricle",
    "Foramen of Monroe",
    "C"],
    ["mc",
    "Cerebrospinal fluid is re-absorbed by the",
    "Arachnoid Granulations",
    "Choroid Plexus",
    "Foramen of Luschke",
    "Ependymal Cells",
    "Granule Cells",
    "A"],
    ["mc",
    "Which of these is NOT a part of the Lateral Ventricle?",
    "Frontal Horn",
    "Occipital Horn",
    "Atrium",
    "Parietal Horn",
    "Temporal Horn",
    "D"],
    ["mc",
    "Which Layer of cortical neurons gives rise to axons that synapse in the brainstem, spinal cord, and basal ganglia?",
    "Internal Pyramidal (Layer 5)",
    "External Pyramidal (Layer 3)",
    "Internal Granular (Layer 4)",
    "External Granular (Layer 2)",
    "Molecular (Layer 1)",
    "A"],
    ["mc",
    "The majority of cerebrospinal fluid is produced by the _____ within the _____",
    "Ependymal Cells, Subarachnoid Space",
    "Granule Cells, Grey Matter",
    "Choroid Plexus, Ventricles",
    "Ependymal Cells, Ventricles",
    "Choroid Plexus, Subarachnoid Space",
    "C"],
    ["mc",
    "The Direction of Flow of Cerebrospinal fluid is",
    "Arachnoid Granulations → Subarachnoid Space → Lateral Ventricle → Foramen of Monro → Third Ventricle → Cerebral Aqueduct → Fourth Ventricle → Foramina of Luschke/Magende",
    "Lateral Ventricle → Foramen of Monro → Third Ventricle → Cerebral Aqueduct → Fourth Ventricle → Foramina of Luschke/Magende → Subarachnoid Space → Arachnoid Granulations",
    "Foramen of Monro → Lateral Ventricle → Cerebral Aqueduct → Third Ventricle → Foramina of Luschke/Magende → Fourth Ventricle → Subarachnoid Space → Arachnoid Granulations",
    "Lateral Ventricle → Cerebral Aqueduct → Third Ventricle → Foramina of Luschke/Magende → Fourth Ventricle → Foramen of Monro → Subarachnoid Space → Arachnoid Granulations",
    "Cerebral Aqueduct → Foramina of Luschke/Magende → Foramen of Monro → Subarachnoid Space → Lateral Ventricle → Third Ventricle → Fourth Ventricle → Arachnoid Granulations",
    "B"],
    ["mc",
    "Which of the following is NOT found in the Middle Cranial Fossa?",
    "Optic Chiasm",
    "Internal Carotid Artery",
    "Oculomotor Nerve",
    "Midbrain",
    "Cerebellum",
    "E"],
    ["mc",
    "Which meningeal layer extends to the coccyx?",
    "Pia Mater",
    "Dura Mater",
    "Arachnoid Mater",
    "Terminal Mater",
    "None of the Above",
    "B"],
    ["mc",
    "Which bones form the base of the skull?",
    "Occipital, Temporal, Sphenoid",
    "Parietal, Temporal, Occipital",
    "Frontal, Parietal, Temporal",
    "Sphenoid, Occipital, Parietal",
    "Temporal, Occipital, Frontal",
    "A"],
    ["mc",
    "What is the major function of the Granular cells of the Inner Granular Layer (Layer 4)?",
    "Receive INPUT from the Thalamus",
    "Direct OUTPUT to the Body",
    "COMMISSURAL between hemispheres",
    "INTERNEURONS between cortical layers within the gyrus",
    "ASSOCIATION between gyri in the same hemisphere",
    "D"],
    ["mc",
    "What are the myelin-producing cells of the CNS?",
    "Fibrous Astrocytes",
    "Protoplasmic Astrocytes",
    "Oligodendrocytes",
    "Schwann Cells",
    "Microglial Cells",
    "C"],
    ["mc",
    "The meningeal layer containing cerebrospinal fluid in normal individuals is the",
    "Epidural Space",
    "Dural Sinus",
    "Subdural Space",
    "Subarachnoid Space",
    "Subpial Space",
    "D"],
    ["mc",
    "A 26 year old woman with a history of acne was prescribed Retin-A. Six weeks after using Retin-A at twice the recommended dose, she starts to develop headaches which become more severe, and she develops blurriness of vision. The headaches are worse lying down than sitting up. She sees an ophthalmologist who looks in her eyes and immediately admits her to neurologist. The most likely problem is",
    "Migraine with visual symptoms affecting the occipital lobes",
    "Bilateral orbital masses",
    "An optic chiasm lesion",
    "Diffuse increased intracranial pressure",
    "Unilateral subdural hematomas",
    "D"],
    ["A 70 year old man is on blood thinners, and he slips and falls and bangs his head. He develops headache and left sided weakness. On examination he has increased tone and increased reflexes on the left. He complains of a severe headache. The problem is a(n)",
    "Subdural in the right frontal lobe",
    "Subdural in the left temporal lobe",
    "Subdural in the right temporal lobe",
    "Epidural in the right parietal lobe",
    "Subdural in the right internal capsule",
    "A"],
    ["A 30 year old patient was in a fight. He was injured on the right side of his head. He is initially fine, but over the next 2-3 hours he develops a worsening headache with left sided weakness. He becomes unresponsive. On examination, he has left sided hemiparesis and a blown pupil on right side. . The problem is a(n)",
    "Subdural in the right parietal lobe",
    "Subdural in the left temporal lobe",
    "Subdural in the right temporal lobe",
    "Epidural in the right frontal lobe",
    "Subdural in the right internal capsule",
    "D"]
];













