var questions = [
    ["mc",
    "The retina consists of _____ cellular layers, of which photoreceptors are located in the _____ layer.",
    "3, Bipolar Cell",
    "5, Outer Nuclear",
    "7, Inner Plexiform",
    "9, Ganglion Cell",
    "4, Outer Plexiform",
    "B"],
    ["mc",
    "The area of greatest concentration of photoreceptors in the retina is the",
    "Macula",
    "Optic Disc",
    "Fovea",
    "Lens",
    "Optic Nerve",
    "C"],
    ["mc",
    "An image visible in the RIGHT UPPER QUADRANT of the visual field will follow what trajectory of information processing?",
    "Inferior Nasal Right Retina → Medial Right Optic Nerve →Left Optic Tract →Left Meyer’s Loop →Left Lingula",
    "Superior Temporal Right Retina →Lateral Right Optic Nerve →Right Optic Tract →Right Superior Optic Radiation →Right Cuneus",
    "Inferior Nasal Left Retina → Lateral Left Optic Nerve → Left Optic Tract →Left Superior Optic Radiation →Left Cuneus",
    "Inferior Temporal Right Retina →Medial Right Optic Nerve →Right Optic Tract →Right Meyer’s Loop → Right Lingula",
    "Superior Temporal Left Retina →Lateral Left Optic Nerve →Left Optic Tract →Left Meyer’s Loop →Left Cuneus",
    "A"],
    ["mc",
    "Axons that form Meyer’s Loop contain visual information from the _____ visual field around the _____ horn of the lateral ventricle.",
    "Superior, Frontal",
    "Inferior, Temporal",
    "Superior, Occipital",
    "Inferior, Frontal",
    "Superior, Temporal",
    "E"],
    ["mc",
    "The primary visual cortex consists of the cuneus and lingula, which surround the _____ fissure.",
    "Parieto-Occipital",
    "Sylvian",
    "Rolandic",
    "Central",
    "Calcarine",
    "E"],
    ["mc",
    "A mass lesion in the pituitary infundibulum would most likely cause what visual disturbance?",
    "Inferior Homonymous Quadrantopia",
    "Left Homonymous Hemianopia",
    "Bitemporal Hemianopia",
    "Scotoma",
    "Right Homonymous Hemianopia",
    "C"],
    ["mc",
    "Name the cranial nerves that exit the brainstem at the level of the midbrain",
    "Oculomotor (III)",
    "Trochlear (IV)",
    "Trigeminal (V)",
    "A and B",
    "All of the Above",
    "D"],
    ["mc",
    "The motor portion of the Trigeminal Nerve exits the cranium through the",
    "Superior Orbital Fissure",
    "Jugular Foramen",
    "Foramen Ovale",
    "Foramen Rotundum",
    "Foramen Lacerum",
    "C"],
    ["mc",
    "The type(s) of nerve fibers found in the Oculomotor nerve include",
    "Somatic Motor",
    "Somatic Sensory",
    "Parasympathetic",
    "Sympathetic",
    "More than one of the above is correct",
    "E"],
    ["mc",
    "The Nucleus Ambiguus give rise to which of the following Cranial Nerves?",
    "Glossopharyngeal (IX)",
    "Vestibulocochlear (VIII)",
    "Hypoglossal (XII)",
    "Facial (VII)",
    "Spinal Accessory (XI)",
    "A"],
    ["mc",
    "A lesion in the Right Trochlear Nucleus will cause the _____ eye to be deviated _____ and _____.",
    "Right, Down, Out",
    "Left, Down, Out",
    "Right, Up, In",
    "Left, Up, In",
    "Left, Up, Out",
    "E"],
    ["mc",
    "The cranial nerve that exits from the posterior brainstem is the",
    "Hypoglossal (XII)",
    "Trochlear (IV)",
    "Trigeminal (V)",
    "Abducens (VI)",
    "Facial (VII)",
    "B"],
    ["mc",
    "Cranial nerves are part of the _____ nervous system and are therefore associated with _____ as their myelin-producing cells.",
    "Central, Oligodendrocytes",
    "Peripheral, Oligodendrocytes",
    "Peripheral, Schwann Cells",
    "Central, Schwann Cells",
    "None of the Above",
    "C"],
    ["mc", 
    "A 70 y/o female presents to her doctor complaining of R eye visual loss. This has been intermittent, occurring a few times per day but not every day. She states that she has complete loss of vision in her right eye only. It is painless, last for less than a minute and returns slowly as if “the lights are coming on slowly in a dark room.” Her examination shows normal pupillary function, eye movements and normal visual acuity. There are no other findings in her exam except a rumbling over the right side of her neck noticeable only with the stethoscope. The patient also tells you that the right side of her jaw feels tired if she chews “tough food.” The most likely cause of her visual loss is:", 
    "Right optic neuritis", 
    "Right cortical stroke", 
    "Right carotid disease", 
    "Right orbit disease", 
    "Right sided migraine",
    "C"],
    ["mc",
    "A 65 y/o male presents to the ER with intermittent L visual loss. He says that he feels as if a shade is coming over his left eye. This will last as long as 30 minutes and resolve spontaneously. Yesterday, the visual loss became full, and he noticed some pain behind his L eye. His examination shows no pupillary reflex on the left, decreased visual acuity on the left and an inability to move his L eye fully to the outside and double vision when looking to the L. There are no other findings. The most likely explanation for the visual complaints is:",
    "Left carotid disease",
    "Left cortical stroke",
    "Left carotid disease",
    "Left orbit disease",
    "Left sided migraine",
    "D"]
];