var questions = [
    ["mc",
    "Which of the following statements is true?",
    "The Oculomotor nerve (III) controls all extraocular muscles",
    "The Optic nerve (II) controls the pupillary constrictor muscle",
    "The Abducens nerve (VI) controls the lateral rectus muscle",
    "The Trochlear nerve (IV) controls the inferior oblique muscle",
    "The Oculomotor nerve is responsible for Abduction of the eye",
    "C"],
    ["mc",
    "A patient with head tilt down and to the right would have a lesion affecting which muscle?",
    "Left Superior Oblique",
    "Right Inferior Rectus",
    "Left Medial Rectus",
    "Right Lateral Rectus",
    "Right Superior Oblique",
    "A"],
    ["mc",
    "In a Right Optic nerve lesion, a light shone into the right eye would cause _____ of the right pupil and _____ of the left pupil",
    "Dilation, Constriction",
    "No response, No response",
    "Dilation, Dilation",
    "No response, Dilation",
    "Constriction, No response",
    "B"],
    ["mc",
    "Internuclear Ophthalmoplegia affects the _____ and disrupts input to the _____ medial rectus muscle.",
    "Medial Longitudinal Fasciculus, Contralateral",
    "Paramedian Pontine Reticular Formation, Contralateral",
    "Abucens Nerve, Ipsilateral",
    "Paramedian Pontine Reticular Formation, Ipsilateral",
    "Medial Longitudinal Fasciculus, Ipsilateral",
    "E"],
    ["mc",
    "An infarct (lesion) affecting the Right frontal eye field would cause _____ gaze deviation.",
    "Rightward",
    "Leftward",
    "Downward",
    "Upward",
    "Inward",
    "A"],
    ["mc",
    "What are the hallmarks of Horner’s Syndrome?",
    "Mydriasis, Exophthalmos, Hyperhidrosis",
    "Miosis, Ptosis, Anhidrosis",
    "Mydriasis, Dysautonomia, Afferent Pupillary Defect",
    "Exotropia, Exophthalmos, Extortion",
    "Miosis, Esotropia, Presbyopia",
    "B"],
    ["mc",
    "First-order (preganglionic) parasympathetic neurons that control pupillary constriction have axons that synapse in the ",
    "Edinger-Westphal Nucleus",
    "Superior Cervical Ganglion",
    "Pretectal Nucleus",
    "Ciliary Ganglion",
    "Lateral Geniculate Nucleus",
    "D"],
    ["mc",
    "Which muscle does NOT originate from a common tendinous ring in the orbital apex?",
    "Superior Rectus",
    "Inferior Rectus",
    "Medial Rectus",
    "Lateral Rectus",
    "They all originate from the common tendinous ring",
    "E"],
    ["mc",
    "Which nerve controls the muscle that Adducts the eye?",
    "Oculomotor (III)",
    "Trochlear (IV)",
    "Abducens (VI)",
    "Optic (II)",
    "None of the Above",
    "A"],
    ["mc",
    "A patient with neurosyphilis may have a pupil that will _____ but not _____.",
    "Accommodate, React",
    "Adduct, Abduct",
    "React, Accommodate",
    "Abduct, Adduct",
    "Dilate, Constrict",
    "A"],
    ["mc",
    "A 22 year-old Right Handed female presents with acute-onset double vision. Her exam is notable for inability to look to the left in her right eye, while the left eye exhibits abnormal shaking in left gaze. This has never happened before, but she remembers having complete numbness of her right side lasting a few days 3 or 4 years ago. The most likely location of the current lesion is",
    "Left medial lemniscus",
    "Right Oculomotor nerve",
    "Right Medial Longitudinal Fasciculus",
    "Right medial rectus muscle",
    "Left Abducens nucleus",
    "C"],
    ["mc",
    "A 79 year-old Left Handed male presents with a history of frequent falls and increased visual difficulty over 3 months, such that his reading glasses are not helping anymore. On exam, he exhibits a mild 4-6 Hz pill-rolling tremor in his left hand and is unable to look down on EOM testing. However, when you manually tilt his head back and forth, his eyes appear to move well in all directions. What is the most likely cause of his frequent falls?",
    "Macular degeneration of the retina",
    "Neurodegeneration in Brainstem nuclei",
    "Mass Compressing bilateral frontal lobes",
    "Stroke in occipital lobe",
    "Infection involving both eyes",
    "B"]
];















