var questions = [
    ["A 25 year-old man has had several concussions throughout his football career. He is rushed into the ER after being tackled by an opponent.  He presents with aphasia, dilation of his left pupil, and nausea. Where is the damage in his brain?",
    "Right hemisphere occipital lobe",
    "Bilateral frontal lobes",
    "Basal ganglia",
    "Cerebellum",
    "Left hemisphere parietal lobe", 
    "B"],
    ["A patient has trouble making decisions and refraining from saying inappropriate comments. Where could the lesion be located?",
    "Occipital cortex",
    "Temporal cortex", 
    "Parietal cortex", 
    "Prefrontal cortex", 
    "Cerebellum",
    "D"],
    ["A patient has conduction aphasia. He cannot produce appropriate responses to heard communication, and has difficulty naming pictures and objects. Where is his lesion located?", 
    "Broca's area", 
    "The arcuate fasiculus", 
    "The primary auditory cortex", 
    "Wernicke's area", 
    "MGN of the thalamus",
    "B"],
    ["A 64-year-old man with diabetes has double vision and his left eye has a downward abducted position. His left eyelid is droopy and the left pupil is dilated. Upon neurologic exam, the neurologist suspects that there is a lesion in which cranial nerve?", 
    "Oculomotor nerve", 
    "Optic nerve", 
    "Trochlear nerve", 
    "Facial nerve", 
    "Olfactory nerve",
    "A"],
    ["A 48 year-old woman with no previous history of major health complications is exhibiting partial facial paralysis on her right side, which started that day. When the patient is asked to raise her eyebrows, the right side does not move nearly as much as the left. Upon examination, the doctor requests an EMG. The results show that there is presence of nerve damage. Which cranial nerve is damaged?",
     "Abducens nerve", 
     "Trigeminal nerve", 
     "Vestibulocochlear nerve", 
     "Trochlear nerve", 
     "Facial nerve",
     "E"],
    ["As part of a neurologic exam, a doctor rotates the head from side to side of a comatose patient and observes her eye movements. What is the doctor testing for?", 
    "Auditory nerve lesion", 
    "Abducens nerve lesion", 
    "Vestibulocochlear nerve lesion", 
    "Trigminal nerve lesion", 
    "Facial nerve lesion",
    "C"],
    ["An 18-year-old girl had her wisdom teeth extracted two weeks ago. She is experiencing numbness and pain in her left jaw. What could be cause of the pain?", 
    "Damage to the hypoglossal nerve", 
    "Damage to the trochlear nerve", 
    "Damage to the glossopharyngeal nerve", 
    "Damage to the facial nerve", 
    "Damage to the trigeminal nerve",
    "E"],
    ["A patient is asked to stick out their tongue, and it deviates to the right side. What could be the cause?",
    "Left hypoglossal nerve lesion",
    "Right glossopharyngeal nerve lesion",
    "Right hypoglossal nerve lesion",
    "Left glossopharyngeal nerve lesion",
    "Left vagus nerve lesion",
    "C"],
    ["A patient is asked to shrug his shoulders, and the left shoulder shrugs normally, but the right is weak. What could be the cause?",
    "Right accessory nerve lesion",
    "Left accessory nerve lesion",
    "Left vestibulocochlear nerve lesion",
    "Right vestibulocochlear nerve lesion",
    "Left glossopharyngeal nerve lesion",
    "A"],
    ["A patient’s gag reflex is weak on one side. What could be the cause?",
    "Accessory nerve lesion",
    "Trigeminal nerve lesion",
    "Glossopharyngeal nerve lesion",
    "Hypoglossal nerve lesion",
    "Trochlear nerve lesion",
    "C"],
    ["A patient presents with a resting tremor. With which pathway could there be a problem?",
    "Medial lemniscal pathway",
    "Extrapyramidal pathway",
    "Spinothalamic pathway",
    "Vestibulospinal pathway",
    "Corticospinal pathway",
    "B"],
    ["Which of the following could be a sign of a lower motor neuron lesion, but would not be a sign of an upper motor neuron lesion?",
    "Weakness",
    "Babinski’s sign",
    "Increased tone",
    "Spasticity",
    "Muscle atrophy",
    "E"],
    ["Which could be a sign of a upper motor neuron lesion, but would not be a sign of a lower motor neuron lesion?",
    "Muscle atrophy",
    "Fasciculations",
    "Decreased tone",
    "Paralysis",
    "Hyperreflexia",
    "E"],
    ["What is a normal rating of a deep tendon reflex?",
    "3/5",
    "5/5",
    "1/5",
    "2/5",
    "0/5",
    "D"],
    ["Which is an example of a reflex normally seen in healthy adult patients?",
    "Brachioradialis reflex",
    "Babinski’s sign",
    "Hoffman’s sign",
    "Frontal release signs",
    "Myerson’s sign",
    "A"],
    ["Abnormal posturing is seen in coma patients with damage to upper motor neuron pathways. Which type of abnormal posturing does not require brainstem function?",
    "Unilateral flexor posturing",
    "Triple flexion",
    "Bilateral extensor posturing",
    "Bilateral flexor posturing",
    "Unilateral extensor posturing",
    "B"],
    ["Which of the following tests does not test appendicular coordination in the neurologic exam?",
    "Rapid alternating movements",
    "Heel-shin test",
    "Overshoot",
    "Romberg test",
    "Finger-nose-finger test",
    "D"],
    ["What is being tested in the coordination and gait exam of the neurologic exam?",
    "Proprioception and vestibular systems",
    "Upper motor neurons",
    "Basal ganglia",
    "Cerebellum",
    "All of the above",
    "E"],
    ["What is something that is not tested for in the coma exam?",
    "Withdrawal from a painful stimulus",
    "Pupillary responses",
    "Apraxia",
    "Posturing reflexes",
    "Caloric testing",
    "C"],
    ["Mr. Jones is a 70 year-old retired college professor. Recently his wife noticed he is different— he’s forgetting things, having difficulty finding words, and his personal appearance is becoming sloppy. Yesterday, she became concerned while driving to the supermarket, as he became lost and could no longer find his way. On examination Mr. Jones is awake, alert, oriented, speech is fluent, but he has difficulty with naming objects, has difficulty with describing/following 3 step commands, and has difficulty with pointing to different body parts. He also has bilateral grasp reflex. The rest of the exam is unremarkable. The most likely area affected is (are) the",
    "Bilateral frontal lobes",
    "Dominant hemisphere frontal lobe",
    "Limbic cortex",
    "Bilateral temporal lobes",
    "Dominant hemisphere temporal lobe",
    "A"]
];













