var questions = [
    ["mc",
    "The primary motor cortex is located in the _____, while the primary somatosensory cortex lies in the _____.",
    "Precentral gyrus, Postcentral gyrus",
    "Postcentral gyrus, Precentral gyrus",
    "Angular gyrus, Paracentral gyrus",
    "Cingulate gyrus, Supramarginal gyrus",
    "Precentral gyrus, Superior Temporal gyrus",
    "A"],
    ["mc", 
    "Axons from pyramidal cells in the primary motor cortex synapse in the ", 
    "Thalamus", 
    "Medullary Pyramid", 
    "Motor Brainstem nuclei",  
    "Dorsal Root Ganglion",
    "Carotid Sinus",
    "C"],
    ["mc",
    "The projection of motor/action impulses for limb movement follows which pathway?",
    "α-motoneuron axon → Pyramidal Decussation → Anterior Horn → Lateral Corticospinal Tract → Corona Radiata → Internal Capsule → Primary Motor Cortex",
    "Primary Motor Cortex → α-motoneuron axon → Corona Radiata → Pyramidal Decussation → Internal Capsule → Lateral Corticospinal Tract → Anterior Horn",
    "Corona Radiata → Pyramidal Decussation → Anterior Horn → Lateral Corticospinal Tract → Internal Capsule → α-motoneuron axon → Primary Motor Cortex",
    "Primary Motor Cortex → Corona Radiata → Internal Capsule → Pyramidal Decussation → Lateral Corticospinal Tract → Anterior Horn → α-motoneuron axon",
    "Internal Capsule → Primary Motor Cortex → Pyramidal Decussation → Corona Radiata → Anterior Horn → Lateral Corticospinal Tract → α-motoneuron axon",
    "D"],
    ["mc",
    "Axons that carry vibration and proprioception sensation from the upper limbs synapse in the",
    "Thalamus",
    "Gracile Nucleus",
    "Cuneate Nucleus",
    "Precentral Gyrus",
    "Postcentral Gyrus",
    "C"],
    ["mc",
    "A lesion in the Left corticospinal fibers at the level of the Pons will result in",
    "Right hemiplegia",
    "Left hemiplegia",
    "Paraplegia",
    "Right monoplegia involving upper extremity",
    "Left monoplegia involving lower extremity",
    "A"],
    ["mc",
    "First-order sensory neurons are _____ neurons with their cell bodies in the ______",
    "Unipolar, Dorsal Root Ganglion",
    "Bipolar, Gracile Nucleus",
    "Multipolar, Dorsal Horn",
    "Bipolar, Dorsal Root Ganglion",
    "Unipolar, Tract of Lissauer",
    "D"],
    ["mc",
    "Where would you expect to find a lesion in a patient with loss of pain and temperature sensation localized to bilateral upper limbs?",
    "Dorsal Columns of upper thoracic spinal cord",
    "Bilateral paracentral lobules of Cortex",
    "Ventral White Commissure of cervical spinal cord",
    "Peripheral Nerves of bilateral upper limbs",
    "Dominant precentral gyrus of Cortex",
    "C"],
    ["mc",
    "The regions of the primary motor cortex responsible for movement of the lower extremity is located in the ",
    "Precentral Gyrus",
    "Postcentral Gyrus",
    "Angular Gyrus",
    "Paracentral Lobule",
    "Superior Parietal Lobule",
    "D"],
    ["mc",
    "Of the following, where would a lesion result in complete Right hemianesthesia (loss of vibration, proprioception, pain, temperature and light touch)?",
    "Dorsal Horn of Left cervical spinal cord",
    "Dorsal Root ganglion of Right Thoracic spinal cord",
    "Left Medial lemniscus of Pons",
    "Precentral Gyrus of Right Hemisphere",
    "Ventral Posterolateral Nucleus of Left Thalamus",
    "E"],
    ["mc",
    "A lesion in the Right primary motor cortex would have which effect on function of facial muscles?",
    "Ipsilateral lower facial paralysis",
    "Contralateral lower facial paralysis",
    "Ipsilateral complete facial paralysis",
    "Contralateral complete facial paralysis",
    "None – the face receives input from both hemispheres",
    "B"],
    ["mc",
    "Upper extremity positioning in Upper Motor Neuron Syndrome is described as",
    "Flaccid, pronated and extended",
    "Flaccid, supinated and extended",
    "Spastic, pronated and flexed",
    "Spastic, supinated and flexed",
    "Spastic, supinated and extended",
    "D"],
    ["mc",
    "Somatosensory fibers containing impulses for pressure and vibration are described as",
    "Myelinated, medium diameter, medium velocity Aβ",
    "Unmyelinated, medium diameter, fast velocity Aδ",
    "Myelinated, small diameter, slow velocity Aα",
    "Unmyelinated, large diameter, slow velocity C",
    "Myelinated, large diameter, fast velocity Aδ",
    "A"],
    ["mc",
    "Second order interneurons carrying pain and temperature sensation synapse in the",
    "Dorsal Tract of Lissauer",
    "Dorsal Horn of Spinal Cord",
    "Cuneate Nucleus",
    "Gracile Nucleus",
    "Ventral Posterolateral Nucleus of Thalamus",
    "E"],
    ["mc",
    "According to the sensory homunculus, which area of the body receives the greatest representation in the cortex?",
    "Arm",
    "Leg",
    "Hand",
    "Face",
    "Genitalia",
    "D"],
    ["mc",
    "A 17 year-old female is brought by friends to the emergency department with acute-onset Rightsided weakness which was present when she awoke this morning. She had stayed at the friend’s home overnight for a slumber party. On exam, she is drowsy but able to respond, with gaze deviation to the left, a right facial droop and inability to move her right arm or leg. She had been incontinent of urine, and there is fresh blood in her mouth from a tongue laceration. She is able to say in slurred speech that she forgot to take her Keppra last night. What is the most likely etiology of her symptoms?",
    "Acute hemorrhage in the left frontal lobe",
    "Acute ischemic infarct (stroke) in the left middle cerebral artery territory",
    "Traumatic injury to the right spinal cord",
    "Post-ictal (Todd’s) paralysis from complex partial seizure",
    "Malingering",
    "D"],
    ["mc",
    "A 42 year-old vegan male presents for evaluation of gait imbalance with increased frequency of falls. His exam is notable for absent pin-prick, vibration and juxtapositional sensation in bilateral lower extremities to the knees and decreased sensation in bilateral upper extremities to the wrists. Routine lab work shows a hematocrit of 26 with a mean corpuscular volume of 110. The best initial treatment option for this condition is",
    "Lumbar Laminectomy",
    "Vitamin B12 supplementation",
    "Physical Therapy",
    "Blood Transfusion",
    "Corticosteroids",
    "B"]
];













