var questions = [
    ["mc",
    "A 26 year-old computer programmer presents to clinic complaining of right hand numbness for several weeks. The numbness is worse at night and wakes her up. On examination she cannot close her fist fully and has numbness in the thumb, II-III digits and half of her ring finger. The most likely location for the lesion is:",
    "The median nerve at the upper arm",
    "The ulnar nerve",
    "The radial nerve",
    "The median nerve at the wrist",
    "The median nerve at the forearm", 
    "D"],
    ["mc",
    "A 30 year-old construction worker is brought to the emergency room with inability to walk. Earlier in the day he was working on his knees while laying down paving stones. He complains of back pain. His examination shows inability to evert his L foot and inability to dorsiflex the same foot. Inversion and flexion are intact. There is some decrease to pin prick over the top of his L foot. There are no reflex changes. The most likely problem is:",
    "A L L5 root compression",
    "A L S1 root compression",
    "A L posterior tibial nerve problem",
    "A L common peroneal problem",
    "A L sciatic proble",
    "D"],
    ["mc",
    "A painter comes to clinic complaining of right sided arm pain and neck pain. On examination, he has a patch of decreased pin sensation over his right upper arm, a decreased biceps reflex and weakness on bending his arm in. The most likely lesion is at",
    "C6",
    "C5",
    "Right brachial plexus",
    "R musculocutaneous nerve",
    "R median nerve",
    "B"],
    ["mc",
    "A police office presents to clinic with a complaint of numbness over his right thigh. Examination shows no weakness. There are no reflex changes. He has hypersensitivity over his right lateral thigh from the midline to the outside of his thigh which does not involve the knee. The most likely lesion is in the",
    "L4 root",
    "Lumbar plexus",
    "Femoral nerve",
    "Lateral femoral cutaneous nerve",
    "Obturator nerve",
    "D"],
    ["mc",
    "You are asked to see an IV drug user who presents with 2 days of severe leg pain bilaterally. Yesterday the patient developed urinary and fecal incontinence. Your examination reveals weakness in both legs below the knees, decreased sensation in the feet and decreased sensation around the groin and buttock area. The most likely area of the lesion is at",
    "L5 roots",
    "Lumbar plexuses",
    "Cauda equina",
    "Conus medullaris",
    "No lesion. Patient is malingering",
    "D"],
    ["mc",
    "A patient with bladder cancer present to the emergency room complaining of left leg pain. On examination, there is weakness of hip flexion, knee extension and sensory loss in the groin. The knee jerk is decreased on the left but normal on the right. The most likely site of the problem is",
    "The L3 nerve root on the left",
    "Spinal cord",
    "The L5 and S1 nerve roots",
    "The left lumbar plexus",
    "The L3, L4 and L5 nerve roots on the left",
    "D"],
    ["mc",
    "Your friend is helping you move in. The next day he complains of bilateral leg numbness below the knees. He has no weakness. Later in the day he tells you that he is having problems urinating. Examination shows no weakness or reflex changes. He has decreased sensation in both feet on the outside and (he is a close friend) over the groin. The most likely site of the problem is",
    "Bilateral peroneal nerve compressions",
    "Bilateral sciatic nerve problems",
    "Conus compression at L3",
    "Conus compression at L5",
    "He is being ridiculous. There is nothing wrong with him.",
    "D"],
    ["mc",
    "A patient with a history of breast cancer presents to clinic complaining of right sided arm pain. Examination shows weakness and fasciculations of the biceps and forearm muscles. She has sensory loss over the biceps, and forearm and also the little finger and ring finger.  Her reflexes are depressed in the biceps and brachioradialis, but not the triceps. The most likely site of the problem is",
    "Right C5 and C6 roots",
    "Right musculocutaneous and ulnar nerve",
    "Right brachial plexus",
    "Right C5, C6, C7 roots",
    "None of the above",
    "C"],
    ["mc",
    "A patient presents with fatigue and difficulty swallowing. Examination reveals minimal weakness throughout, absent reflexes and no sensory changes. You notice a lid droop bilaterally. The most likely explanation is that the patient has",
    "Motor neuron disease",
    "A diffuse brain process",
    "A neuromuscular junction disorder",
    "A brainstem process affecting the glossopharyngeal and hypoglossal nerve",
    "Peripheral neuropathy",
    "C"],
    ["mc",
    "A patient presents with numbness in the feet and hands. He has a history of alcohol abuse. Examination shows wasting of the legs, no fasciculations, no clear weakness, absent reflexes in the ankles, decreased knee jerks, normal upper extremity reflexes and decreased pin, light touch and vibratory sensation symmetrically below the knees and in the fingetips. The most likely problem is",
    "Lumbar cord lesion at L5",
    "Cervical cord lesion at C7",
    "Bilateral L5 and S1 root problems",
    "Peripheral nerve damage",
    "Bilateral lumbar plexus lesions",
    "D"],
    ["mc",
    "A patient presents with difficulty walking. Examination shows no clear weakness. Reflexes are very brisk throughout. There is loss of vibration sensation but no changes in pin or light touch. The most likely area involved is",
    "The peripheral nerves",
    "The posterior columns",
    "The spinocerebellar tracts",
    "The anterior spinothalamic tracts",
    "B"],
    ["mc",
    "Your best friend and you spend a night “on the town.” When you wake up the next morning you can’t lift your right wrist. Your friend is convinced you had a stroke and wants to take you to the ER. Knowing your neuroanatomy you tell him that you don’t have a stroke,  after noticing that you have weakness but no sensory changes, but do have",
    "A median nerve compression",
    "An ulnar nerve compression",
    "A radial nerve compression",
    "A brachial plexus compression",
    "A cervical root compression at C6",
    "C"]
];













